USE master;
GO

IF DB_ID(N'ReferenceData') IS NULL
    EXEC(N'CREATE DATABASE ReferenceData COLLATE ${COLLATION}');
IF DB_ID(N'Trading') IS NULL
    EXEC(N'CREATE DATABASE Trading COLLATE ${COLLATION}');
IF DB_ID(N'Orders') IS NULL
    EXEC(N'CREATE DATABASE Orders COLLATE ${COLLATION}');
IF DB_ID(N'Risk') IS NULL
    EXEC(N'CREATE DATABASE Risk COLLATE ${COLLATION}');
GO

ALTER DATABASE ReferenceData SET COMPATIBILITY_LEVEL = ${COMPATIBILITY_LEVEL};
ALTER DATABASE Trading SET COMPATIBILITY_LEVEL = ${COMPATIBILITY_LEVEL};
ALTER DATABASE Orders SET COMPATIBILITY_LEVEL = ${COMPATIBILITY_LEVEL};
ALTER DATABASE Risk SET COMPATIBILITY_LEVEL = ${COMPATIBILITY_LEVEL};
GO
